name: driverroute_eta
description: DriverRoute Arrival/ETA – Flutter MVP
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.5.0
  intl: ^0.20.2
  timezone: ^0.9.2
  shared_preferences: ^2.3.2
  google_maps_flutter: ^2.5.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  uuid: ^4.5.1

# optional (später):
# flutter_polyline_points: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fahrplaene/ferries.json
